name: Milestone Labeler
on:
  issues:
    types: [milestoned]
permissions:
  contents: read

jobs:
  apply_labels:
    permissions:
      issues: write  # for andymckay/labeler to label issues
      pull-requests: write  # for andymckay/labeler to label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Add track-internal
        uses: andymckay/labeler@1.0.4
        if: github.event.issue.pull_request == null
        with:
          repo-token: ${{ secrets.Github_Token }}
          add-labels: "track-internal"
